cmake_minimum_required(VERSION 3.10)
project(elosa CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()
find_package(Threads REQUIRED)
add_executable(elosa src/elosa.cpp)
target_link_libraries(elosa Threads::Threads)
if(NOT MSVC)
  target_compile_options(elosa PRIVATE -O3 -march=native)
endif()
set_target_properties(elosa PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin)
